### ISSUE TITLE
Content Management System

### ISSUE THREAD

**Issue by flexdevelopment** [flex-development/cospark#4]
# Overview

## Problem statement

**Describe the problem you're trying to solve by doing this work.**

After handoff, the client would like a way to update the marketing site without the help of a developer. This includes managing website settings, uploading new content, and editing existing copy.

## Proposed work

**High-level overview of what we're building and why we think it will solve the problem.**

One one of the following content management systems should be implemented:

**[Forestry](https://forestry.io/)**
Forestry is a Git-backed content management system for static site generators like Gatsby and Jekyll. Quite a few successful websites and products have been built using the CMS, and some teams have even seen an increase in website performance.

**[Sanity Studio](https://www.sanity.io/studio)**
Sanity Studio is a React based content management system that integrates with [Gatsby Cloud](https://www.gatsbyjs.com/cloud/).

> Sanity.io is configured with simple JavaScript and can be further customized
using React. If your team is ready to make a website with Gatsby, they’ll also
quickly get started with Sanity.

# Success criteria

**The criteria that must be met in order to consider this project a success.** 

- [x]  Choose content management system
- [x]  Implement a content management system
    - [x]  Manage website settings
    - [x]  Edit existing content
    - [x]  Add new content
- [x] Replace mock data with CMS data
- [x] Create static pages using Gatsby’s Node.js `createPage` API

# User stories

**How the product should work for various user types.**

## **User type 1 — End User**

- End users should see content updates after refreshing their page (may or may not need to empty their cache)
- Content should be **accessible**

## **User type 2 — Editor**

- Add new content
- Edit existing website content

## **User type 3 — Admin**

- Edit website metadata and settings
- Manage website menus
- Set user permissions

## User type 4 - Developer

- See `Editor` & `Admin` user types

# Scope

## Requirements

**Current project requirements.**

- Implement a CMS that can be operated after project handoff

## Future work

**Future requirements.**

- Launch web application

## Non-requirements

**List anything that is out of scope.**

- Integrate CMS with web application

# Designs

**Include designs here or add directly to the Requirements or User Stories sections.** 

N/A

# Alternatives considered

**List any alternatives you considered to this approach. Explain why they weren't used.**

N/A

# Related documents

**Include links to other pages as necessary (e.g. technical design doc, project proposal, etc.)**

N/A

**Comment by lexusdrumgold** [comment]
Instead of creating pages programmatically, pages using the `interior-page` template will be written in MDX, using Forestry CMS.
